-- F3/F4. Executar somente em Postgres LOCAL ou isolado; ROLLBACK ao final.
begin;
create function pg_temp.recusa_f3(comando text,codigo text) returns boolean language plpgsql as $$
begin execute comando;return false;exception when others then if sqlstate=codigo then return true;end if;raise;end $$;
create function pg_temp.testar_f3_f4() returns table(teste text,ok boolean) language plpgsql as $$
declare u uuid:=gen_random_uuid();u2 uuid:=gen_random_uuid();ua uuid:=gen_random_uuid();us uuid:=gen_random_uuid();m uuid;m2 uuid;ma uuid;c uuid;c2 uuid;p uuid;comp uuid;privado_comp uuid;d uuid;a uuid;a2 uuid;manual uuid;comando text;inicio_real timestamptz;j jsonb;
begin
 insert into auth.users(id,email,email_confirmed_at,aud,role) values(u,'f3@example.test',now(),'authenticated','authenticated'),(u2,'f3outro@example.test',now(),'authenticated','authenticated'),(ua,'f3admin@example.test',now(),'authenticated','authenticated'),(us,'f3sem@example.test',now(),'authenticated','authenticated');
 insert into public.membros(user_id,nome,nome_curto,email,papel,acesso_clientes,acesso_agenda) values(u,'Autor F3','Autor F3','f3@example.test','associado','editar','todas') returning id into m;
 insert into public.membros(user_id,nome,nome_curto,email,papel,acesso_clientes,acesso_agenda) values(u2,'Outro F3','Outro F3','f3outro@example.test','socio','editar','propria') returning id into m2;
 insert into public.membros(user_id,nome,nome_curto,email,papel) values(ua,'Admin F3','Admin F3','f3admin@example.test','admin') returning id into ma;
 insert into public.membros(user_id,nome,nome_curto,email,papel,acesso_clientes,acesso_agenda) values(us,'Sem F3','Sem F3','f3sem@example.test','secretaria','nenhum','todas');
 insert into public.clientes(nome) values('Cliente F3') returning id into c;insert into public.clientes(nome) values('Outro cliente F3') returning id into c2;
 insert into public.processos(cliente_id,titulo,area) values(c,'Caso F3','civel') returning id into p;
 insert into public.compromissos(cliente_id,membro_id,tipo,modalidade,inicio,fim) values(c,m,'atendimento','presencial',now(),now()+interval '1 hour') returning id into comp;
 insert into public.compromissos(cliente_id,membro_id,tipo,modalidade,inicio,fim,particular) values(c,m2,'atendimento','presencial',now(),now()+interval '1 hour',true) returning id into privado_comp;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u)::text,true);perform set_config('role','authenticated',true);
 insert into public.documentos(modelo,titulo,cliente_id,processo_id,dados,conteudo) values('procuracao','PROCURAÇÃO',c,p,'{}','<p>Texto final</p>') returning id into d;
 return query select 'Documento salva texto final e autor do servidor',exists(select 1 from public.documentos where id=d and criado_por=m and conteudo='<p>Texto final</p>');
 return query select 'Texto salvo é imutável',pg_temp.recusa_f3(format('update public.documentos set conteudo=''Alterado'' where id=%L',d),'42501');
 return query select 'Cliente e título salvos são imutáveis',pg_temp.recusa_f3(format('update public.documentos set cliente_id=%L,titulo=''Falso'' where id=%L',c2,d),'42501');
 return query select 'Documento não pode ser apagado',pg_temp.recusa_f3(format('delete from public.documentos where id=%L',d),'42501');
 return query select 'Documento recusa processo de outro cliente',pg_temp.recusa_f3(format('insert into public.documentos(modelo,titulo,cliente_id,processo_id,conteudo) values(''procuracao'',''Falso'',%L,%L,''Texto'')',c2,p),'P0001');
 return query select 'Cancelamento de documento exige motivo',pg_temp.recusa_f3(format('update public.documentos set cancelado_em=now() where id=%L',d),'P0001');
 update public.documentos set cancelado_em='2000-01-01',motivo_cancelamento='Erro de teste' where id=d;
 return query select 'Cancelamento preserva texto e carimba quem e quando',exists(select 1 from public.documentos where id=d and cancelado_por=m and cancelado_em>'2026-01-01' and conteudo='<p>Texto final</p>');
 return query select 'Cancelado não pode ser reaberto',pg_temp.recusa_f3(format('update public.documentos set cancelado_em=null where id=%L',d),'P0001');
 return query select 'Documento entra na auditoria do módulo',exists(select 1 from public.auditoria where tabela='documentos' and registro_id=d and acao='cancelou');
 a:=public.iniciar_cronometro(jsonb_build_object('cliente_id',c,'processo_id',p,'tipo','atendimento_presencial','compromisso_id',comp,'membro_id',m2,'inicio','2000-01-01'));
 select inicio into inicio_real from public.atualizacoes where id=a;
 return query select 'Início ignora data e autor enviados e usa relógio do servidor',exists(select 1 from public.atualizacoes where id=a and inicio>clock_timestamp()-interval '1 minute' and membro_id=m and cronometrado and fim is null);
 return query select 'Iniciar atendimento registra chegada',exists(select 1 from public.compromissos where id=comp and chegada_em is not null);
 return query select 'Não permite dois cronômetros para o mesmo membro',pg_temp.recusa_f3(format('select public.iniciar_cronometro(%L::jsonb)',jsonb_build_object('cliente_id',c)),'P0001');
 j:=public.meu_cronometro();return query select 'RPC sincroniza atividade e relógio do servidor',j->'atualizacao'->>'id'=a::text and j->>'agora' is not null;
 return query select 'Fim futuro do cronômetro é recusado',pg_temp.recusa_f3(format('select public.parar_cronometro(%L,null,null,now()+interval ''1 day'')',a),'P0001');
 return query select 'Fim anterior ao início é recusado',pg_temp.recusa_f3(format('select public.parar_cronometro(%L,null,null,%L::timestamptz-interval ''1 minute'')',a,inicio_real),'P0001');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u2)::text,true);
 return query select 'Outro membro consulta relato e não altera atividade alheia',exists(select 1 from public.atualizacoes where id=a);
 update public.atualizacoes set relato='Intruso' where id=a;return query select 'RLS protege alteração de outro autor',exists(select 1 from public.atualizacoes where id=a and relato is null);
 return query select 'Outro membro não para cronômetro alheio',pg_temp.recusa_f3(format('select public.parar_cronometro(%L)',a),'42501');
 a2:=public.iniciar_cronometro(jsonb_build_object('cliente_id',c));return query select 'Pessoas distintas podem ter relógios simultâneos',a2<>a and (public.meu_cronometro()->'atualizacao'->>'id')=a2::text;
 perform public.parar_cronometro(a2);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u)::text,true);
 perform public.parar_cronometro(a,'Relato concluído','Conferir documentos');
 return query select 'Parada preserva marcador e registra relato, providência e fim',exists(select 1 from public.atualizacoes where id=a and fim>=inicio and cronometrado and relato='Relato concluído' and proxima_providencia='Conferir documentos');
 return query select 'Parada conclui atendimento vinculado',exists(select 1 from public.compromissos where id=comp and situacao='realizado');
 return query select 'RPC não deixa sinal de parada para alterações seguintes',coalesce(current_setting('fhl.cronometro',true),'')<>'parar';
 update public.atualizacoes set fim=inicio where id=a;return query select 'Correção de horário retira marcador e registra antes e depois',exists(select 1 from public.atualizacoes where id=a and not cronometrado) and exists(select 1 from public.auditoria where registro_id=a and antes->>'cronometrado'='true' and depois->>'cronometrado'='false');
 return query select 'Atividade concluída não pode reabrir relógio',pg_temp.recusa_f3(format('update public.atualizacoes set fim=null where id=%L',a),'P0001');
 return query select 'Marcador cronômetro não pode ser forjado por INSERT',pg_temp.recusa_f3(format('insert into public.atualizacoes(cliente_id,membro_id,tipo,inicio,fim,cronometrado) values(%L,%L,''pesquisa'',now(),now(),true)',c,m),'42501');
 return query select 'Lançamento manual exige fim',pg_temp.recusa_f3(format('insert into public.atualizacoes(cliente_id,membro_id,tipo,inicio) values(%L,%L,''pesquisa'',now())',c,m),'P0001');
 return query select 'Autor não pode ser transferido por PATCH',pg_temp.recusa_f3(format('update public.atualizacoes set membro_id=%L where id=%L',m2,a),'42501');
 insert into public.atualizacoes(cliente_id,membro_id,participantes,tipo,inicio,fim) values(c,m,array[m2],'pesquisa',now(),now()) returning id into manual;
 return query select 'Anotação sem tempo e participante são aceitos',exists(select 1 from public.atualizacoes where id=manual and inicio=fim and participantes=array[m2] and not cronometrado);
 return query select 'Autor repetido entre participantes é recusado',pg_temp.recusa_f3(format('update public.atualizacoes set participantes=array[%L::uuid] where id=%L',m,manual),'P0001');
 return query select 'Participante repetido é recusado',pg_temp.recusa_f3(format('update public.atualizacoes set participantes=array[%L::uuid,%L::uuid] where id=%L',m2,m2,manual),'P0001');
 return query select 'Cronômetro respeita vínculo cliente/processo',pg_temp.recusa_f3(format('select public.iniciar_cronometro(%L::jsonb)',jsonb_build_object('cliente_id',c2,'processo_id',p)),'P0001');
 return query select 'Cronômetro não acessa atendimento particular de outro membro',pg_temp.recusa_f3(format('select public.iniciar_cronometro(%L::jsonb)',jsonb_build_object('cliente_id',c,'compromisso_id',privado_comp)),'42501');
 a:=public.iniciar_cronometro(jsonb_build_object('cliente_id',c));perform public.parar_cronometro(a,null,null,(select inicio from public.atualizacoes where id=a));
 return query select 'Fim real informado retira marca de cronômetro',exists(select 1 from public.atualizacoes where id=a and not cronometrado and fim=inicio);
 insert into public.documentos(modelo,titulo,cliente_id,atualizacao_id,conteudo) values('ficha_atendimento','FAA',c,manual,'Relato final');
 return query select 'Documento recusa atualização de outro cliente',pg_temp.recusa_f3(format('insert into public.documentos(modelo,titulo,cliente_id,atualizacao_id,conteudo) values(''ficha_atendimento'',''FAA'',%L,%L,''Falso'')',c2,manual),'P0001');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',us)::text,true);
 return query select 'Sem Clientes não lê documentos, relatos ou auditoria',not exists(select 1 from public.documentos where cliente_id=c) and not exists(select 1 from public.atualizacoes where cliente_id=c) and not exists(select 1 from public.auditoria where registro_id=manual);
 return query select 'Sem Clientes não inicia nem sincroniza relógio',pg_temp.recusa_f3(format('select public.iniciar_cronometro(%L::jsonb)',jsonb_build_object('cliente_id',c)),'42501') and pg_temp.recusa_f3('select public.meu_cronometro()','42501');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',ua)::text,true);
 update public.atualizacoes set relato='Correção administrativa' where id=manual;return query select 'Administrador pode corrigir relato de outro autor',exists(select 1 from public.atualizacoes where id=manual and relato='Correção administrativa' and membro_id=m);
 perform set_config('role','none',true);update public.membros set ativo=false where id=m;perform set_config('role','authenticated',true);
 update public.atualizacoes set cancelado_em=now(),motivo_cancelamento='Cancelado pelo admin' where id=manual;return query select 'Admin cancela registros mesmo após autor ficar inativo',exists(select 1 from public.atualizacoes where id=manual and cancelado_por=ma);
 return query select 'Relatos cancelados não podem ser modificados',pg_temp.recusa_f3(format('update public.atualizacoes set relato=''Alterado'' where id=%L',manual),'P0001');
 return query select 'Atualizações não podem ser apagadas',pg_temp.recusa_f3(format('delete from public.atualizacoes where id=%L',manual),'42501');
 perform set_config('role','anon',true);
 return query select 'Anônimo não lê documentos nem relatos',pg_temp.recusa_f3('select * from public.documentos','42501') and pg_temp.recusa_f3('select * from public.atualizacoes','42501');
 return query select 'Anônimo não executa os RPCs de cronômetro',pg_temp.recusa_f3('select public.meu_cronometro()','42501') and pg_temp.recusa_f3('select public.iniciar_cronometro(''{}''::jsonb)','42501');
 perform set_config('role','none',true);
end $$;
select * from pg_temp.testar_f3_f4();
rollback;
